#!/usr/bin/python

def is_even(test_num):
    if test_num % 2 == 0:
        return True
    else:
        return False

def calc_lattice(rolling_num):
    print 'Test Value: %s' %(rolling_num)
    count = 0
    while True:
        print rolling_num
        if rolling_num == 1:
            return count
        elif rolling_num in record_dict.keys():
            print 'Dict Entry Found: %s' %rolling_num
            print 'Dict Value: %s' %record_dict[rolling_num]
            count += record_dict[rolling_num]
            return count
        elif is_even(rolling_num):
            rolling_num = rolling_num/2
            count += 1
        else:
            rolling_num = 3*rolling_num+1

record_dict = {}
test_value = 1

while test_value <= 1000000:
    count = calc_lattice(test_value)
    print(record_dict)
    record_dict[test_value] = count
    test_value += 1
    if test_value == 15:
        break

